on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & Test NEAR Contracts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Kernel Parameters for NEAR
        run: |
          sudo sysctl -w net.core.rmem_max=8388608
          sudo sysctl -w net.core.wmem_max=8388608
          sudo sysctl -w net.ipv4.tcp_rmem="4096 87380 8388608"
          sudo sysctl -w net.ipv4.tcp_wmem="4096 16384 8388608"
          sudo sysctl -w net.ipv4.tcp_slow_start_after_idle=0

      - name: Install Rust & Wasm Target
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
          rustup target add wasm32-unknown-unknown

      - name: Install Binaryen (wasm-opt)
        run: |
          sudo apt update
          sudo apt install -y binaryen

      - name: Run Build and Test Script
        run: |
          chmod +x test.sh
          ./test.sh
